# Generated by Django 5.2.1 on 2025-05-27 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="titel",
            new_name="title",
        ),
    ]
