# Generated by Django 5.1.5 on 2025-01-29 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={"verbose_name_plural": "commentaries"},
        ),
    ]
