# Generated by Django 4.1 on 2024-01-04 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='owner',
            new_name='user',
        ),
    ]
