# Generated by Django 4.1 on 2025-06-13 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="content",
            field=models.TextField(default=None, help_text="Enter your text"),
        ),
    ]
