# Generated by Django 4.1 on 2024-12-17 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="owner",
            new_name="user",
        ),
    ]
