# Generated by Django 4.1 on 2022-12-24 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='content',
            field=models.CharField(max_length=255),
        ),
    ]
