# Generated by Django 5.2.3 on 2025-06-23 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("created_time",)},
        ),
    ]
