# Generated by Django 5.0.6 on 2024-07-05 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
