# Generated by Django 4.1 on 2024-09-11 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='created_at',
            new_name='created_time',
        ),
    ]
