# Generated by Django 4.1 on 2023-03-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={
                "default_related_name": "comments",
                "verbose_name": "commentary",
                "verbose_name_plural": "commentaries",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "default_related_name": "users",
                "verbose_name": "user",
                "verbose_name_plural": "users",
            },
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(),
        ),
    ]
