# Generated by Django 4.1 on 2023-07-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="content",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
