# Generated by Django 5.0.3 on 2024-03-27 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-created_time",)},
        ),
    ]
