# Generated by Django 5.0.3 on 2024-03-19 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="content",
            field=models.CharField(default="need message", max_length=1500),
        ),
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.CharField(default="need message", max_length=1500),
        ),
    ]
