# Generated by Django 4.1 on 2024-05-10 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="author",
            new_name="user",
        ),
    ]
