# Generated by Django 4.1 on 2023-10-29 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='content',
            field=models.TextField(),
        ),
    ]
