# Generated by Django 5.1.1 on 2024-09-13 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="create_time",
            new_name="created_time",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="create_time",
            new_name="created_time",
        ),
    ]
