# Generated by Django 4.1 on 2024-04-01 18:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comentary",
            new_name="Commentary",
        ),
    ]
