# Generated by Django 5.0.1 on 2024-01-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text=(
                    "The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                ),
                related_name="user_groups",
                to="auth.group",
                verbose_name=("Groups",),
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text=("Specific permissions for this user.",),
                related_name="user_permissions",
                to="auth.permission",
                verbose_name=("User permissions",),
            ),
        ),
    ]
