# Generated by Django 5.2.4 on 2025-08-19 00:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="owner",
        ),
    ]
