# Generated by Django 4.1 on 2023-02-21 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="content",
            field=models.TextField(default="comment"),
        )
    ]
