# Generated by Django 5.1 on 2024-09-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="Commentary",
        ),
        migrations.RenameField(
            model_name="commentary",
            old_name="owner",
            new_name="user",
        ),
    ]
