# Generated by Django 4.1 on 2023-02-04 09:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={"verbose_name_plural": "commentaries"},
        ),
    ]
