# Generated by Django 5.0.1 on 2024-01-21 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='Commentary',
        ),
    ]
