# Generated by Django 4.1 on 2023-05-14 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="content",
            field=models.TextField(max_length=1500),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=1500),
        ),
    ]
