# Generated by Django 4.1 on 2025-01-12 14:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["title", "-created_time"]},
        ),
        migrations.AlterField(
            model_name="commentary",
            name="content",
            field=models.TextField(
                validators=[django.core.validators.MaxLengthValidator(800)]
            ),
        ),
        migrations.AlterField(
            model_name="commentary",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.post",
            ),
        ),
    ]
