# Generated by Django 4.1 on 2024-06-19 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={
                "ordering": ["created_time"],
                "verbose_name_plural": "Commentaries",
            },
        ),
    ]
