# Generated by Django 4.2 on 2025-01-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="updated_time",
        ),
    ]
