# Generated by Django 5.1.5 on 2025-01-26 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="user",
            new_name="owner",
        ),
    ]
