# Generated by Django 4.2.6 on 2023-10-26 09:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={
                "verbose_name": "commentary",
                "verbose_name_plural": "commentaries",
            },
        ),
        migrations.RemoveField(
            model_name="post",
            name="owner",
        ),
        migrations.AddField(
            model_name="post",
            name="owner",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
