# Generated by Django 4.2 on 2023-05-09 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=250, unique_for_date="publish"
            ),
        ),
    ]
