# Generated by Django 4.1 on 2024-09-17 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"ordering": ("username",)},
        ),
    ]
