# Generated by Django 4.1 on 2025-09-28 19:43

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Comment",
            new_name="Commentary",
        ),
    ]
