# Generated by Django 4.1 on 2025-10-28 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="crated_time",
            new_name="created_time",
        ),
    ]
