# Generated by Django 4.1 on 2023-04-30 08:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="content",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
