# Generated by Django 4.1 on 2023-03-22 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_options_alter_commentary_created_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'verbose_name_plural': 'commentaries'},
        ),
    ]
