# Generated by Django 4.1 on 2023-02-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("blog", "0002_commentary_content")]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="content",
            field=models.TextField(default=":-)"),
        )
    ]
