# Generated by Django 4.1 on 2023-08-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_commentary_created_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='content',
            field=models.TextField(default=None),
        ),
    ]
