# Generated by Django 4.1 on 2024-01-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_commentary_post_alter_commentary_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="content",
            field=models.TextField(),
        ),
    ]
