# Generated by Django 4.1 on 2023-09-23 18:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_commentary_content"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="created_date",
            new_name="created_time",
        ),
    ]
