# Generated by Django 4.1 on 2023-07-18 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_user_hobby'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'ordering': ['-created_time'], 'verbose_name': 'Commentary', 'verbose_name_plural': 'Commentaries'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_time']},
        ),
    ]
