# Generated by Django 5.1.1 on 2024-11-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_user_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="created_time",
            new_name="created_datetime",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="created_time",
            new_name="created_datetime",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                verbose_name="active",
            ),
        ),
    ]
