# Generated by Django 4.1 on 2025-03-12 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_commentary_created_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentary',
            options={'ordering': ['created_time'], 'verbose_name_plural': 'commentaries'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_time']},
        ),
    ]
