# Generated by Django 4.1.5 on 2023-01-25 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_created_at_post_created_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={
                "ordering": ["-created_time", "post", "user"],
                "verbose_name_plural": "commentaries",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_time", "title", "owner"]},
        ),
        migrations.AlterField(
            model_name="commentary",
            name="created_time",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
