# Generated by Django 4.1 on 2023-03-08 20:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_commentary_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={"ordering": ["-created_time"], "verbose_name_plural": "comments"},
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
