# Generated by Django 5.1.5 on 2025-01-26 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_user_post_owner"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="create_time",
            new_name="created_time",
        ),
    ]
