# Generated by Django 5.1.5 on 2025-01-29 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_commentary_options"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="owner",
            new_name="user",
        ),
    ]
