# Generated by Django 4.2.6 on 2023-10-26 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_commentary_options_remove_post_owner_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commentary",
            name="post",
        ),
        migrations.RemoveField(
            model_name="commentary",
            name="user",
        ),
        migrations.AddField(
            model_name="commentary",
            name="post",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentaries",
                to="blog.post",
            ),
        ),
        migrations.AddField(
            model_name="commentary",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="commentaries",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
