# Generated by Django 4.1 on 2023-09-04 19:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_commentary_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_time"]},
        ),
    ]
