# Generated by Django 4.1 on 2024-04-07 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_user_options_alter_commentary_content_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="created_time",
        ),
    ]
