# Generated by Django 4.2 on 2024-02-22 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_commentary_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-created_time",)},
        ),
    ]
