# Generated by Django 4.2.2 on 2023-06-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0002_alter_post_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="content",
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(max_length=300),
        ),
    ]
