# Generated by Django 4.1 on 2024-09-11 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_created_at_commentary_created_time'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='created_time',
        ),
    ]
