# Generated by Django 4.1 on 2024-12-30 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_rename_created_at_post_created_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="created_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_time",
            field=models.DateTimeField(),
        ),
    ]
