# Generated by Django 4.1 on 2024-11-07 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_commentary_options_alter_post_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={
                "ordering": ["-created_time"],
                "verbose_name": "commentary",
                "verbose_name_plural": "commentarys",
            },
        ),
    ]
