# Generated by Django 4.2 on 2024-09-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_post_created_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="created_time",
        ),
    ]
