# Generated by Django 5.1.5 on 2025-01-26 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_create_time_post_created_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={"verbose_name_plural": "Comments"},
        ),
        migrations.AlterField(
            model_name="commentary",
            name="created_time",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="post",
            name="created_time",
            field=models.DateTimeField(),
        ),
    ]
