# Generated by Django 4.1 on 2024-04-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_commentary_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={"verbose_name": "commentary", "verbose_name_plural": "comments"},
        ),
    ]
