# Generated by Django 4.2.2 on 2023-06-06 17:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_commentary_content_alter_post_content"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={
                "verbose_name": "commentary",
                "verbose_name_plural": "commentaries",
            },
        ),
    ]
