# Generated by Django 5.1.5 on 2025-01-29 18:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_owner_commentary_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={
                "ordering": ["-created_time"],
                "verbose_name_plural": "commentaries",
            },
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_time", "title"]},
        ),
        migrations.AlterField(
            model_name="post",
            name="created_time",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
