# Generated by Django 5.0.1 on 2024-01-25 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_commentary_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentary',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, max_length=255),
        ),
    ]
