# Generated by Django 5.2.1 on 2025-05-16 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_comment_commentary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='created_at',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='created_time',
        ),
    ]
