# Generated by Django 4.1 on 2025-09-03 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_post_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='content',
            field=models.TextField(default='No content'),
        ),
    ]
