# Generated by Django 4.1 on 2023-02-25 14:26

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_alter_commentary_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={
                "ordering": ("-created_time",),
                "verbose_name_plural": "commentaries",
            },
        ),
    ]
