# Generated by Django 5.1.1 on 2024-11-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_created_time_commentary_created_datetime_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="created_datetime",
            new_name="created_time",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="created_datetime",
            new_name="created_time",
        ),
    ]
