# Generated by Django 4.1 on 2023-07-18 13:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_commentary_options_alter_post_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentary',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to='blog.post'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commentary',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='commentaries', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
