# Generated by Django 4.1 on 2024-12-30 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_commentary_created_at_alter_post_created_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="created_at",
            new_name="created_time",
        ),
    ]
