# Generated by Django 4.1 on 2025-08-19 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_rename_comment_commentary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="author",
            new_name="user",
        ),
    ]
