# Generated by Django 4.1 on 2025-03-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_commentary_content"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="content",
            field=models.TextField(),
        ),
    ]
