# Generated by Django 4.1 on 2023-09-23 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_rename_created_date_post_created_time"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("created_time",)},
        ),
        migrations.AlterField(
            model_name="commentary",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="blog.post",
            ),
        ),
    ]
