# Generated by Django 4.2.6 on 2023-10-26 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0003_remove_commentary_post_remove_commentary_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="commentary",
            name="created_time",
            field=models.DateTimeField(),
        ),
    ]
