# Generated by Django 4.1 on 2024-05-23 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_commentary_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
    ]
