# Generated by Django 4.1 on 2023-05-27 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_commentary_post"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="contents",
        ),
        migrations.AddField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="commentary",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
