# Generated by Django 4.2 on 2024-09-09 09:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_remove_post_created_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="created_time",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
