# Generated by Django 5.1.5 on 2025-01-29 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_commentary_options_alter_post_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_time"]},
        ),
    ]
