# Generated by Django 4.1 on 2024-04-01 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_commentary_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="created_time",
            field=models.CharField(max_length=63),
        ),
    ]
