# Generated by Django 4.1 on 2023-11-21 21:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0004_alter_commentary_post_alter_commentary_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={"ordering": ["-created_time"]},
        ),
    ]
