# Generated by Django 4.1 on 2024-10-27 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_commentary_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentary',
            old_name='created_at',
            new_name='created_time',
        ),
    ]
