# Generated by Django 4.1 on 2023-03-26 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blog", "0005_alter_commentary_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={"ordering": ["created_time"]},
        ),
    ]
