# Generated by Django 4.2 on 2024-09-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_created_time"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="created_at",
            new_name="created_time",
        ),
    ]
