# Generated by Django 4.1 on 2024-04-01 21:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0006_alter_post_created_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="commentary",
            name="created_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
