# Generated by Django 4.2 on 2024-09-11 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_alter_commentary_post_alter_commentary_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="commentary",
            options={"ordering": ["-created_time"]},
        ),
    ]
