# Generated by Django 4.1 on 2025-10-20 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="commentary",
            old_name="created_at",
            new_name="created_time",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="created_at",
            new_name="created_time",
        ),
    ]
